pcm.dante {
    type plug
    slave.pcm "dante_mono"

    hint {
        show on
        description "Mono Dante output via Inferno"
    }
}

pcm.dante_mono {
    type route
    slave.pcm "inferno_raw"
    slave.channels 1

    # Stereo L/R zu Mono mischen:
    # Links  -> Mono mit 50 %
    # Rechts -> Mono mit 50 %
    ttable.0.0 0.5
    ttable.1.0 0.5
}

pcm.inferno_raw {
    type inferno

    hint {
        show on
        description "Raw Inferno Dante PCM"
    }
}
